### ISSUE TITLE
[Camping and Furniture] Probably problem with some languages

### ISSUE THREAD

**Issue by Tehemo** [satisfyu/Let-s-Do-Hub#235]
### Minecraft Version

1.20.1 Fabric

### Mod

Camping

### Mod Version

1.0.2

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Crash on Startup. Probably because of my local language because if you add "-Duser.country=US -Duser.language=en" to java arguments game starts without a problem. I didn't want to create seperate issue since both mods have the same problem, please tell me if I need to create them and I apologize if I need to open a separate issue.

### Steps to Reproduce

Set your local language Turkish and start game.

### Logs

[Let's Do] Camping -> https://pastebin.com/k1TeRqYC
[Let's Do] Furniture -> https://pastebin.com/QLsrYstZ

after adding "-Duser.country=US -Duser.language=en" arguments -> https://pastebin.com/SuBPbAnF

### Minimal Instance Test

- [X] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Can't be reproduced. Also your logs don't show anything useful.

**Comment by Tehemo** [comment]
At first sorry for late response, fortunetly there is useful information in crash report.

for camping: https://pastebin.com/P8pi5ANa 
As can be seen, the capital “i” make the error.

for furniture: https://pastebin.com/y9DuXXL6
It's same for furniture, "İ" makes problem.

**Comment by satisfyu** [comment]
Thank you for your patience. I guess i've found and fixed the Issue. :)

**Comment by satisfyu** [comment]
Fixed in 1.0.4 Camping and 1.0.3 Furniture.

**Comment by Tehemo** [comment]
Thanks! I can use Camping mod now but unfortunately still the same problem for Furniture.

Crash report: https://pastebin.com/2rsbc574

**Comment by satisfyu** [comment]
Whoops, sorry. I didn't push that change before i've released it. I'll fix that withing the next week -sorry!

**Comment by Tehemo** [comment]
Thanks for your attention. Keep up the good work!

**Comment by MCoutercraft** [comment]
Hello, I have the same issue with the furniture mod.

The user friend of mine is also from Turkey so I am certain it is the same issue. 

May we have it fixed? I saw the mod didn't get updated the week after your response was made.

I really appriciate your work and I am a huge fan of your content <3.

Thank you a lot for your effort and time :)!

**Comment by MCoutercraft** [comment]
Hello,

I am really sorry for this kind of comment, I dont mean to be annoying but really just wanted to ask politely when I could expect this previous mentioned issue to be resolved as my friend cannot join my server because of it.

With the current bug, she crashes shortly after joining. 

I know you already are working on a lot of things, but is it possible to push for a quick hotfix? I would greatly appriciate it :)! If not, how far behind in the backlog is this current bug? Just to make some expectations on when we get to play together with this mod..

I wish you a very nice day!

Best,
A fan

**Comment by Poopooracoocoo** [comment]
I believe the fix is as simple as using Locale.ROOT for toLowerCase and toUpperCase

**Comment by Tehemo** [comment]
> Hello,
> 
> I am really sorry for this kind of comment, I dont mean to be annoying but really just wanted to ask politely when I could expect this previous mentioned issue to be resolved as my friend cannot join my server because of it.
> 
> With the current bug, she crashes shortly after joining.
> 
> I know you already are working on a lot of things, but is it possible to push for a quick hotfix? I would greatly appriciate it :)! If not, how far behind in the backlog is this current bug? Just to make some expectations on when we get to play together with this mod..
> 
> I wish you a very nice day!
> 
> Best, A fan

You can fix that problem if you really hopeless by putting "-Duser.country=US -Duser.language=en" in Java arguments. But be carefull you cannot enter your singleplayer (not sure about multiplayer) world that you create before doing this.

**Comment by satisfyu** [comment]
Fixed in 1.0.4
