### ISSUE TITLE
Vinery recipes not appearing in creative or JEI

### ISSUE THREAD

**Issue by Corn-on-the-Orb** [satisfyu/Let-s-Do-Hub#25]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.19

### Issue Description

I cant seem to find out why or how to even go about fixing this but certain recipes and items do not appear at all in the creative menu or in JEI despite the items still existing in game. Most items work fine in the menus, but certain ones like the banner you get from completing all achievements simply doesnt appear at all in any of the menus. 

### Steps to Reproduce

.

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [x] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
That was intended first because it should be some sort of a 'suprise' for players to get. Therefore a few items didn't show up in the creative tab hidden. However, i've just added them. Therefore, this Issue should be fixed. :)

**Comment by Corn-on-the-Orb** [comment]
ah i see thank you for clarifying, I was just confused because on other [Let's Do] mods they did appear in creative tab and i just wanted to make sure there wasnt something wrong.

**Comment by Corn-on-the-Orb** [comment]
which version is this supposed to be fixed for, because I am on the latest version and the problem is still there. The main reason I want these items is for making quest steps and I can't use it as a step if I can't select it
