### ISSUE TITLE
Vinery causes crash when using bonemeal on Farmer's Delight rice crop

### ISSUE THREAD

**Issue by kennahco** [satisfyu/Let-s-Do-Hub#382]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.30

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

Using bonemeal on the Rice crop from Farmer's Delight Refabricated (2.2.4) crashes server with error 'Exception in server tick loop'. Error is found at 
"knot//net.minecraft.class_1752.handler$dhj000$vinery$useOnBlock(class_1752.java:1028)" so I suspect some issue with Vinery conflicting with Farmer's Delight.

### Steps to Reproduce

Start server with Vinery and Farmer's Delight Refabricated installed (Fabric loader). Plant rice in water. Use bonemeal on rice.

### Logs

https://pastebin.com/DVsm560S

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by kennahco** [comment]
Actually, upon further playing this seems to happen with any Farmer's Delight crop (tomatoes, onions etc.)

**Comment by satisfyu** [comment]
Fixed in 1.4.31

**Comment by kennahco** [comment]
Crash still happening in 1.4.31. Tried with and without armor on in case that had anything to do with it; it crashes both ways.
Crash log: https://pastebin.com/0Re6C53R

**Comment by satisfyu** [comment]
Should be finally fixed in 1.4.32
