### ISSUE TITLE
Crash on version 1.4.32

### ISSUE THREAD

**Issue by GayLuluMain** [satisfyu/Let-s-Do-Hub#387]
### Minecraft Version

1.20.1

### Mod

Vinery

### Mod Version

1.4.32

### Latest Version

- [X] Yes. I'm using the latest Version.

### Issue Description

The mod crashes upon me launching my game. I do not ever see the main menu. If I roll the version back to the last recommended release on curseforge, the game launches. 

### Steps to Reproduce

Launch the game.

### Logs

https://pastebin.com/JfaG68pf

### Minimal Instance Test

- [x] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [X] Yes, I have checked for similar issues.

**Comment by GayLuluMain** [comment]
I've found out via removing other mods that the issue is that Tetranomicon is broken by the newest update to Vinery, for reasons beyond me. Removing either fixes it.

**Comment by satisfyu** [comment]
The crash you had was because you're using an outdated version of nethervinery. 1.2.15 should fix this.

**Comment by GayLuluMain** [comment]
> The crash you had was because you're using an outdated version of nethervinery. 1.2.15 should fix this.

Updating nethervinery allowed me to re-enable that mod, but Tetranomicon will still crash it if enabled.

**Comment by satisfyu** [comment]
Do you have a log for this?

**Comment by satisfyu** [comment]
This issue is being closed due to missing and unsubmitted information, particularly because no crash log was provided.

Feel free to reach out once you can provide a crash log, and I will reopen the issue.
