### ISSUE TITLE
All problem with the new version of meadow

### ISSUE THREAD

**Issue by Aasgrim** [satisfyu/Let-s-Do-Hub#446]
### Minecraft Version

1.20.1

### Mod

Meadow

### Mod Version

1.3.20

### Latest Version

- [x] Yes. I'm using the latest Version.

### Issue Description

Update to the newest version 

All my cheeses are gone from my cheese rack 
the pine shelves are bugged as hell and i can"t put out item without duplicating them
I can"t open the shelves that have a block on them

### Steps to Reproduce

Just use all those block and update to the newest version in the same world

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [x] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
Thank you for your bug report. The duplication of items was caused by an incorrect parameter in the `createMenu` method. I have fixed this issue.

The problem with all blocks displaying rendered items disappearing is related to the removal of the previous API used for handling renderers. I attempted to secure this with the specified path, but there is no guarantee.

**Comment by satisfyu** [comment]
Fixed in version 1.3.21. Sorry for the hassle. :(

**Comment by Aasgrim** [comment]
Still has the same problem with the new update

**Comment by Aasgrim** [comment]
Sorry but with the new update there is still the same problem. No cheese in the racks, the shelves are not usable
