### ISSUE TITLE
Player tick issues and not being able to join server

### ISSUE THREAD

**Issue by L00z3r** [satisfyu/Let-s-Do-Hub#537]
### Issue Title

Let's do beachparty

### Minecraft Version

1.20.1

### Mod

Beachparty

### Mod Version

2.0.0

### Latest Version

- [x] Yes. I'm using the latest Version.

### Issue Description

having issues with the rubber ring trinket when players left and try to join the server, the server doesn't allow them to join back because of issues with the trinket.

### Steps to Reproduce

have the beachparty trinket while also having other trinkets from other mods i assume. im not sure if that's why but i've had to reset people's data twice already because of that.

### Logs

Failed to handle packet for /184.52.51.95:62099
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
        at net.satisfy.beachparty.fabric.core.compat.BeachpartyTrinket$RubberRingTrinket.tick(BeachpartyTrinket.java:144) ~[letsdo-beachparty-fabric-2.0.0.jar:?]
        at net.minecraft.class_1309.md2eed77$trinkets$lambda$tick$2$a(class_1309.java:18814) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.7.2.jar:?]
        at net.minecraft.class_1309.md2eed77$trinkets$lambda$tick$3$9(class_1309.java:18759) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1309.handler$ecf00a$trinkets$tick(class_1309.java:18756) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2499) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
        at net.satisfy.beachparty.fabric.core.compat.BeachpartyTrinket$RubberRingTrinket.tick(BeachpartyTrinket.java:144) ~[letsdo-beachparty-fabric-2.0.0.jar:?]
        at net.minecraft.class_1309.md2eed77$trinkets$lambda$tick$2$a(class_1309.java:18814) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.7.2.jar:?]
        at net.minecraft.class_1309.md2eed77$trinkets$lambda$tick$3$9(class_1309.java:18759) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1309.handler$ecf00a$trinkets$tick(class_1309.java:18756) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2499) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 9 more
[17:39:32] [Server thread/WARN]: Failed to handle packet for /184.52.51.95:62099
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
        at net.satisfy.beachparty.fabric.core.compat.BeachpartyTrinket$RubberRingTrinket.tick(BeachpartyTrinket.java:144) ~[letsdo-beachparty-fabric-2.0.0.jar:?]
        at net.minecraft.class_1309.md2eed77$trinkets$lambda$tick$2$a(class_1309.java:18814) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.7.2.jar:?]
        at net.minecraft.class_1309.md2eed77$trinkets$lambda$tick$3$9(class_1309.java:18759) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1309.handler$ecf00a$trinkets$tick(class_1309.java:18756) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2499) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
        at net.satisfy.beachparty.fabric.core.compat.BeachpartyTrinket$RubberRingTrinket.tick(BeachpartyTrinket.java:144) ~[letsdo-beachparty-fabric-2.0.0.jar:?]
        at net.minecraft.class_1309.md2eed77$trinkets$lambda$tick$2$a(class_1309.java:18814) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.7.2.jar:?]
        at net.minecraft.class_1309.md2eed77$trinkets$lambda$tick$3$9(class_1309.java:18759) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1309.handler$ecf00a$trinkets$tick(class_1309.java:18756) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2499) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 9 more
[17:39:32] [Server thread/WARN]: Failed to handle packet for /184.52.51.95:62099
net.minecraft.class_148: Ticking player
        at net.minecraft.class_3222.method_14226(class_3222.java:574) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_18784(class_3244.java:269) ~[server-intermediary.jar:?]
        at net.minecraft.class_2535.method_10754(class_2535.java:259) ~[server-intermediary.jar:?]
        at net.minecraft.class_3242.method_14357(class_3242.java:172) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:908) ~[server-intermediary.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_746
        at net.satisfy.beachparty.fabric.core.compat.BeachpartyTrinket$RubberRingTrinket.tick(BeachpartyTrinket.java:144) ~[letsdo-beachparty-fabric-2.0.0.jar:?]
        at net.minecraft.class_1309.md2eed77$trinkets$lambda$tick$2$a(class_1309.java:18814) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.7.2.jar:?]
        at net.minecraft.class_1309.md2eed77$trinkets$lambda$tick$3$9(class_1309.java:18759) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1309.handler$ecf00a$trinkets$tick(class_1309.java:18756) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2499) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 9 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_746
        at net.satisfy.beachparty.fabric.core.compat.BeachpartyTrinket$RubberRingTrinket.tick(BeachpartyTrinket.java:144) ~[letsdo-beachparty-fabric-2.0.0.jar:?]
        at net.minecraft.class_1309.md2eed77$trinkets$lambda$tick$2$a(class_1309.java:18814) ~[server-intermediary.jar:?]
        at dev.emi.trinkets.api.LivingEntityTrinketComponent.forEach(LivingEntityTrinketComponent.java:362) ~[trinkets-3.7.2.jar:?]
        at net.minecraft.class_1309.md2eed77$trinkets$lambda$tick$3$9(class_1309.java:18759) ~[server-intermediary.jar:?]
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
        at net.minecraft.class_1309.handler$ecf00a$trinkets$tick(class_1309.java:18756) ~[server-intermediary.jar:?]
        at net.minecraft.class_1309.method_5773(class_1309.java:2499) ~[server-intermediary.jar:?]
        at net.minecraft.class_1657.method_5773(class_1657.java:283) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_14226(class_3222.java:510) ~[server-intermediary.jar:?]
        ... 9 more
[17:39:32] [Server thread/INFO]: kentao_22 lost connection: Internal server error
[17:39:32] [Server thread/INFO]: kentao_22 left the game

### Minimal Instance Test

- [ ] Yes, I've tested on a minimal instance.

### Check for Similar Issues

- [ ] Yes, I have checked for similar issues.

**Comment by satisfyu** [comment]
This has been fixed in Dev. Thanks for reporting the bug and sorry for the inconvenience :)

**Comment by netcore10** [comment]
There's an issue here that still persists, we crashed in our server when entering water.

[2025-04-06-1 (1).log](https://github.com/user-attachments/files/19639884/2025-04-06-1.1.log)

**Comment by tejras** [comment]
Sorry for asking but how can I get the dev build? We’re having that exact issue on our server rn

**Comment by satisfyu** [comment]
Fixed in 2.0.1. If the same issue comes up again, feel free to write again and I’ll reopen this issue. :)
